server:
  port: 8912

spring:
  application:
    name: spring-cloud-eureka-cus

  #gateway配置
  cloud:
    gateway:
      routes:
      - id: root
        # uri:lb表示从注册中心订阅服务。
        uri: lb://spring-cloud-eureka-pro
        predicates:
          - Path=/api/**
        filters:
          - StripPrefix=1
          #熔断过滤器
          - name: Hystrix
            args:
              name: fallback
              fallbackUri: forward:/fallback



eureka:
#  instance:
#    hostname: peer3
  client:
    #registerWithEureka 和 fetchRegistry 设置为false，表明自己属于服务中心主体
    registerWithEureka: true #是否将自己注册到eureka server，构建集群环境时，需将自己注册到集群中，默认为true
    fetchRegistry: true #是否从eureka server获取注册信息，构建集群环境时，需同步其他eureka server节点，默认为true
    serviceUrl:
      defaultZone: http://127.0.0.1:8910/eureka/


